# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"o\n\x0e\x41nalyzeRequest\x12\x17\n\x0f\x64\x65\x63lared_sender\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0c\n\x04urls\x18\x04 \x03(\t\x12\x17\n\x0fhas_attachments\x18\x05 \x01(\x08\"\xa8\x01\n\x0f\x41nalyzeResponse\x12\x12\n\nrisk_level\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x0f\n\x07reasons\x18\x03 \x03(\t\x12\x33\n\x05\x66lags\x18\x04 \x03(\x0b\x32$.analysis.AnalyzeResponse.FlagsEntry\x1a,\n\nFlagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x32J\n\x08\x41nalyzer\x12>\n\x07\x41nalyze\x12\x18.analysis.AnalyzeRequest\x1a\x19.analysis.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZERESPONSE_FLAGSENTRY']._loaded_options = None
  _globals['_ANALYZERESPONSE_FLAGSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=139
  _globals['_ANALYZERESPONSE']._serialized_start=142
  _globals['_ANALYZERESPONSE']._serialized_end=310
  _globals['_ANALYZERESPONSE_FLAGSENTRY']._serialized_start=266
  _globals['_ANALYZERESPONSE_FLAGSENTRY']._serialized_end=310
  _globals['_ANALYZER']._serialized_start=312
  _globals['_ANALYZER']._serialized_end=386
# @@protoc_insertion_point(module_scope)
